/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.*;

/**
 *
 * @author jefte
 */
public class AgregarPelicula extends javax.swing.JFrame {
    
    HashMap<Integer, Pelicula> mapaPeliculas;
    HashMap<Integer, Prestamo> mapaPrestamos;
    HashMap<String, Trabajador> mapaTrabajadores;

    /**
     * Creates new form AgregarPelicula
     */
    public AgregarPelicula(HashMap<Integer, Pelicula> mapaPelicula, HashMap<Integer, Prestamo> mapaPrestamo, HashMap<String, Trabajador> mapaTrabajador) {
        initComponents();
        mapaPeliculas = mapaPelicula;
        mapaPrestamos = mapaPrestamo;
        mapaTrabajadores = mapaTrabajador;
        setLocationRelativeTo(null);
    }

    private AgregarPelicula() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNombreID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAnioID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDirectorID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGeneroID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPrecioVentaID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrecioArriendoID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtStockID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnAtrasID = new javax.swing.JButton();
        btnAgregarPeliculaID = new javax.swing.JButton();
        btnLimpiarID = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDirector = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtGenero = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPrecioVenta = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPrecioArriendo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnAtrasSinID = new javax.swing.JButton();
        btnAgregarPeliculaSinID = new javax.swing.JButton();
        btnLimpiarSinID = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Agregar Pelicula"));

        jLabel1.setText("ID:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Año:");

        jLabel4.setText("Director:");

        jLabel5.setText("Genero:");

        jLabel6.setText("Precio Venta:");

        jLabel7.setText("Precio Arriendo:");

        jLabel8.setText("Stock:");

        btnAtrasID.setText("Atras");
        btnAtrasID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasIDActionPerformed(evt);
            }
        });

        btnAgregarPeliculaID.setText("Agregar Pelicula");
        btnAgregarPeliculaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPeliculaIDActionPerformed(evt);
            }
        });

        btnLimpiarID.setText("Limpiar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtStockID, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(txtPrecioArriendoID)
                    .addComponent(txtPrecioVentaID)
                    .addComponent(txtGeneroID)
                    .addComponent(txtDirectorID)
                    .addComponent(txtAnioID)
                    .addComponent(txtNombreID)
                    .addComponent(txtId))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnAtrasID)
                .addGap(42, 42, 42)
                .addComponent(btnAgregarPeliculaID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnLimpiarID)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnioID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDirectorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGeneroID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioVentaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPrecioArriendoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStockID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtrasID)
                    .addComponent(btnAgregarPeliculaID)
                    .addComponent(btnLimpiarID))
                .addGap(33, 33, 33))
        );

        jTabbedPane1.addTab("con ID", jPanel1);

        jLabel9.setText("Nombre:");

        jLabel10.setText("Año:");

        jLabel11.setText("Director:");

        jLabel12.setText("Genero:");

        jLabel13.setText("Precio Venta:");

        jLabel14.setText("Precio Arriendo:");

        jLabel15.setText("Stock:");

        btnAtrasSinID.setText("Atras");
        btnAtrasSinID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasSinIDActionPerformed(evt);
            }
        });

        btnAgregarPeliculaSinID.setText("Agregar Pelicula");
        btnAgregarPeliculaSinID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPeliculaSinIDActionPerformed(evt);
            }
        });

        btnLimpiarSinID.setText("Limpiar");
        btnLimpiarSinID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarSinIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtStock, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(txtPrecioArriendo)
                    .addComponent(txtPrecioVenta)
                    .addComponent(txtGenero)
                    .addComponent(txtDirector)
                    .addComponent(txtAnio)
                    .addComponent(txtNombre))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnAtrasSinID)
                .addGap(42, 42, 42)
                .addComponent(btnAgregarPeliculaSinID)
                .addGap(37, 37, 37)
                .addComponent(btnLimpiarSinID)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecioArriendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(52, 167, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAtrasSinID)
                            .addComponent(btnAgregarPeliculaSinID)
                            .addComponent(btnLimpiarSinID))
                        .addGap(33, 33, 33))))
        );

        jTabbedPane1.addTab("sin ID", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasIDActionPerformed
        // TODO add your handling code here:
        Menu oMenu = new Menu(mapaPeliculas, mapaPrestamos, mapaTrabajadores);
        
        this.dispose();
        oMenu.setVisible(true);
        
    }//GEN-LAST:event_btnAtrasIDActionPerformed

    private void btnAgregarPeliculaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPeliculaIDActionPerformed
        // TODO add your handling code here:
        int id;
        
        if( txtId.getText().equals("") || txtNombreID.getText().equals("") || txtAnioID.getText().equals("") || txtDirectorID.getText().equals("") || txtGeneroID.getText().equals("") || txtPrecioVentaID.getText().equals("") || txtPrecioArriendoID.getText().equals("") || txtStockID.getText().equals("")  ) {
        
            JOptionPane.showMessageDialog(this, "Ingrese todos los datos");
        
        } else {
        
            Pelicula oPelicula = new Pelicula();
            
            id = Integer.parseInt(txtId.getText());
            
            //oPelicula.setId(id);
            oPelicula.setNombre(txtNombreID.getText());
            oPelicula.setAnio(Integer.parseInt(txtAnioID.getText()));
            oPelicula.setDirector(txtDirectorID.getText());
            oPelicula.setGenero(txtGeneroID.getText());
            oPelicula.setPrecioVenta(Integer.parseInt(txtPrecioVentaID.getText()));
            oPelicula.setPrecioArriendo(Integer.parseInt(txtPrecioArriendoID.getText()));
            oPelicula.setStock(Integer.parseInt(txtStockID.getText()));
            
            try {
                oPelicula.agregarPelicula(id, oPelicula, mapaPeliculas);
            } catch (SQLException ex) {
                Logger.getLogger(AgregarPelicula.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            txtId.setText("");
            txtNombreID.setText("");
            txtAnioID.setText("");
            txtDirectorID.setText("");
            txtGeneroID.setText("");
            txtPrecioVentaID.setText("");
            txtPrecioArriendoID.setText("");
            txtStockID.setText("");
                
            JOptionPane.showMessageDialog(this, "Pelicula Agregada Correctamente");
        
        }
                    
    }//GEN-LAST:event_btnAgregarPeliculaIDActionPerformed

    private void btnAgregarPeliculaSinIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPeliculaSinIDActionPerformed
        // TODO add your handling code here:
        if( txtNombre.getText().equals("") || txtAnio.getText().equals("") || txtDirector.getText().equals("") || txtGenero.getText().equals("") || txtPrecioVenta.getText().equals("") || txtPrecioArriendo.getText().equals("") || txtStock.getText().equals("")  ) {
        
            JOptionPane.showMessageDialog(this, "Ingrese todos los datos");
        
        } else {
        
            Pelicula oPelicula = new Pelicula();
            
            
            //oPelicula.setId(id);
            oPelicula.setNombre(txtNombre.getText());
            oPelicula.setAnio(Integer.parseInt(txtAnio.getText()));
            oPelicula.setDirector(txtDirector.getText());
            oPelicula.setGenero(txtGenero.getText());
            oPelicula.setPrecioVenta(Integer.parseInt(txtPrecioVenta.getText()));
            oPelicula.setPrecioArriendo(Integer.parseInt(txtPrecioArriendo.getText()));
            oPelicula.setStock(Integer.parseInt(txtStock.getText()));
            
            try {
                oPelicula.agregarPelicula(oPelicula, mapaPeliculas);
            } catch (SQLException ex) {
                Logger.getLogger(AgregarPelicula.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            txtNombre.setText("");
            txtAnio.setText("");
            txtDirector.setText("");
            txtGenero.setText("");
            txtPrecioVenta.setText("");
            txtPrecioArriendo.setText("");
            txtStock.setText("");
                
            JOptionPane.showMessageDialog(this, "Pelicula Agregada Correctamente");
        
        }
        
    }//GEN-LAST:event_btnAgregarPeliculaSinIDActionPerformed

    private void btnAtrasSinIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasSinIDActionPerformed
        // TODO add your handling code here:
        Menu oMenu = new Menu(mapaPeliculas, mapaPrestamos, mapaTrabajadores);
       
        this.dispose();
        oMenu.setVisible(true);
    }//GEN-LAST:event_btnAtrasSinIDActionPerformed

    private void btnLimpiarSinIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarSinIDActionPerformed
        // TODO add your handling code here:
        
        txtNombre.setText("");
        txtAnio.setText("");
        txtDirector.setText("");
        txtGenero.setText("");
        txtPrecioVenta.setText("");
        txtPrecioArriendo.setText("");
        txtStock.setText("");
        
    }//GEN-LAST:event_btnLimpiarSinIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarPelicula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPeliculaID;
    private javax.swing.JButton btnAgregarPeliculaSinID;
    private javax.swing.JButton btnAtrasID;
    private javax.swing.JButton btnAtrasSinID;
    private javax.swing.JButton btnLimpiarID;
    private javax.swing.JButton btnLimpiarSinID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtAnioID;
    private javax.swing.JTextField txtDirector;
    private javax.swing.JTextField txtDirectorID;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtGeneroID;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreID;
    private javax.swing.JTextField txtPrecioArriendo;
    private javax.swing.JTextField txtPrecioArriendoID;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtPrecioVentaID;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtStockID;
    // End of variables declaration//GEN-END:variables
}
