/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.*;

/**
 *
 * @author jefte
 */
public class ModificarPrestamo extends javax.swing.JFrame {
    
    DefaultTableModel oModeloTabla = new DefaultTableModel();
    HashMap<Integer, Pelicula> mapaPeliculas;
    HashMap<Integer, Prestamo> mapaPrestamos;
    HashMap<String, Trabajador> mapaTrabajadores;

    /**
     * Creates new form ModificarPrestamo
     */
    public ModificarPrestamo(HashMap<Integer, Pelicula> mapaPelicula, HashMap<Integer, Prestamo> mapaPrestamo, HashMap<String, Trabajador> mapaTrabajador) {
        initComponents();
        mapaPeliculas = mapaPelicula;
        mapaPrestamos = mapaPrestamo;
        mapaTrabajadores = mapaTrabajador;
        setLocationRelativeTo(null);
        
        oModeloTabla.addColumn("ID");
        oModeloTabla.addColumn("Nombre");
        oModeloTabla.addColumn("Año");
        oModeloTabla.addColumn("Director");
        oModeloTabla.addColumn("Genero");
        
        tblPeliculas.setModel(oModeloTabla);
    }

    private ModificarPrestamo() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdPrestamo = new javax.swing.JTextField();
        btnBuscarPrestamo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtRutCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRutTrabajador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFechaPrestamo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFechaEntrega = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMontoPagar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPeliculas = new javax.swing.JTable();
        btnAtras = new javax.swing.JButton();
        btnLimpiarPrestamo = new javax.swing.JButton();
        btnModificarPrestamo = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIdPelicula = new javax.swing.JTextField();
        txtNombrePelicula = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDirector = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtGenero = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPrecioVenta = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtPrecioArriendo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnBuscarPelicula = new javax.swing.JButton();
        btnLimpiarPelicula = new javax.swing.JButton();
        btnAgregarPelicula = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Ver Prestamo"));

        jLabel1.setText("Id Prestamo");

        btnBuscarPrestamo.setText("Buscar");
        btnBuscarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPrestamoActionPerformed(evt);
            }
        });

        jLabel2.setText("Rut Cliente");

        jLabel3.setText("Rut Trabajador");

        jLabel4.setText("Fecha Prestamo");

        jLabel5.setText("Fecha Entrega");

        jLabel6.setText("Monto a Pagar");

        jLabel7.setText("Peliculas Arrendadas en este Prestamo");

        tblPeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPeliculas);

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnLimpiarPrestamo.setText("Limpiar");
        btnLimpiarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarPrestamoActionPerformed(evt);
            }
        });

        btnModificarPrestamo.setText("Modificar Datos del Prestamo");
        btnModificarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPrestamoActionPerformed(evt);
            }
        });

        jLabel8.setText("Agregar o Eliminar Peliculas al Prestamo");

        jLabel9.setText("Id Pelicula");

        txtNombrePelicula.setEditable(false);

        txtAnio.setEditable(false);

        jLabel12.setText("Nombre");

        jLabel10.setText("Año");

        txtDirector.setEditable(false);

        jLabel11.setText("Director");

        txtGenero.setEditable(false);

        jLabel13.setText("Genero");

        txtPrecioVenta.setEditable(false);

        jLabel14.setText("Precio Venta");

        txtPrecioArriendo.setEditable(false);

        jLabel15.setText("Precio Arriendo");

        txtStock.setEditable(false);

        jLabel16.setText("Stock");

        btnBuscarPelicula.setText("Buscar");
        btnBuscarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPeliculaActionPerformed(evt);
            }
        });

        btnLimpiarPelicula.setText("Limpiar");
        btnLimpiarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarPeliculaActionPerformed(evt);
            }
        });

        btnAgregarPelicula.setText("Agregar Pelicula a Prestamo");
        btnAgregarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPeliculaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnAtras)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFechaPrestamo)
                            .addComponent(txtIdPrestamo)
                            .addComponent(txtRutCliente)
                            .addComponent(txtRutTrabajador)
                            .addComponent(txtFechaEntrega)
                            .addComponent(txtMontoPagar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBuscarPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimpiarPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addComponent(btnModificarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(52, 52, 52)
                                    .addComponent(txtIdPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtStock, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(txtPrecioArriendo)
                                    .addComponent(txtPrecioVenta)
                                    .addComponent(txtGenero)
                                    .addComponent(txtDirector)
                                    .addComponent(txtAnio)
                                    .addComponent(txtNombrePelicula))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBuscarPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimpiarPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgregarPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPrestamo))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnModificarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtRutCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpiarPrestamo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtRutTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMontoPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtIdPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPelicula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombrePelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(btnLimpiarPelicula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(btnAgregarPelicula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPrecioArriendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(btnAtras)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPrestamoActionPerformed
        // TODO add your handling code here:

        for(int i=0; i<tblPeliculas.getRowCount();i++){
            oModeloTabla.removeRow(i);
            i-=1;
        }

        if ( txtIdPrestamo.getText().equals("") ) {

            JOptionPane.showMessageDialog(this, "Ingrese un ID de Prestamo");

        } else {

            Prestamo oPrestamo = new Prestamo();

            oPrestamo = mapaPrestamos.get(Integer.parseInt(txtIdPrestamo.getText()));

            txtIdPrestamo.setEditable(false);
            txtRutCliente.setText(oPrestamo.getRutCliente());
            txtRutTrabajador.setText(oPrestamo.getRutTrabajador());
            txtFechaPrestamo.setText(oPrestamo.getFechaPrestamo());
            txtFechaEntrega.setText(oPrestamo.getFechaEntrega());
            txtMontoPagar.setText(String.valueOf(oPrestamo.getMontoAPagar()));

            HashMap<Integer, Pelicula> mapaPeliculasPrestamos = oPrestamo.mapaPeliculas;
            String [] datosPeliculas = new String[oModeloTabla.getColumnCount()];

            for (Map.Entry<Integer, Pelicula> entry : mapaPeliculasPrestamos.entrySet()) {

                Pelicula oPelicula = new Pelicula();
                oPelicula = entry.getValue();

                datosPeliculas[0] = String.valueOf(oPelicula.getId());
                datosPeliculas[1] = oPelicula.getNombre();
                datosPeliculas[2] = String.valueOf(oPelicula.getAnio());
                datosPeliculas[3] = oPelicula.getDirector();
                datosPeliculas[4] = oPelicula.getGenero();

                oModeloTabla.addRow(datosPeliculas);

            }

        }

    }//GEN-LAST:event_btnBuscarPrestamoActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        Menu oMenu = new Menu(mapaPeliculas, mapaPrestamos, mapaTrabajadores);

        this.dispose();
        oMenu.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnLimpiarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarPrestamoActionPerformed
        // TODO add your handling code here:
        
        txtIdPrestamo.setEditable(true);
        txtIdPrestamo.setText("");
        txtRutCliente.setText("");
        txtRutTrabajador.setText("");
        txtFechaPrestamo.setText("");
        txtFechaEntrega.setText("");
        txtMontoPagar.setText("");

        for(int i=0; i<tblPeliculas.getRowCount();i++){
            oModeloTabla.removeRow(i);
            i-=1;
        }

    }//GEN-LAST:event_btnLimpiarPrestamoActionPerformed

    private void btnModificarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPrestamoActionPerformed
        // TODO add your handling code here:
        
        if ( txtIdPrestamo.getText().equals("") ) {

            JOptionPane.showMessageDialog(this, "Ingrese un ID de Prestamo");

        } else {

            Prestamo oPrestamo = new Prestamo();

            oPrestamo = mapaPrestamos.get(Integer.parseInt(txtIdPrestamo.getText()));

            txtIdPrestamo.setEditable(false);
            
            //Modficando los datos del Prestamo seleccionado
            //no se puede modificar el ID
            //oPrestamo.setIdPrestamo(Integer.parseInt(txtIdPrestamo.getText()));
            oPrestamo.setRutCliente(txtRutCliente.getText());
            oPrestamo.setRutTrabajador(txtRutTrabajador.getText());
            oPrestamo.setFechaPrestamo(txtFechaPrestamo.getText());
            oPrestamo.setFechaEntrega(txtFechaEntrega.getText());
            oPrestamo.setMontoAPagar(Integer.parseInt(txtMontoPagar.getText()));
            
            JOptionPane.showMessageDialog(this, "Se modificaro los datos del Prestamo con ID: "+oPrestamo.getIdPrestamo());
            
            txtIdPrestamo.setText("");
            txtRutCliente.setText("");
            txtRutTrabajador.setText("");
            txtFechaPrestamo.setText("");
            txtFechaEntrega.setText("");
            txtMontoPagar.setText("");
            
            for(int i=0; i<tblPeliculas.getRowCount();i++){
                oModeloTabla.removeRow(i);
                i-=1;
            }
            

        }
        
        txtIdPrestamo.setEditable(true);
        
    }//GEN-LAST:event_btnModificarPrestamoActionPerformed

    private void btnBuscarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPeliculaActionPerformed
        // TODO add your handling code here:
        
        if( txtIdPelicula.getText().equals("") || txtIdPrestamo.getText().equals("") ) {
        
            JOptionPane.showMessageDialog(this, "Ingrese todos los datos");
        
        } else { 
        
            Pelicula oPelicula = new Pelicula();
            
            oPelicula = oPelicula.buscarPelicula(mapaPeliculas, Integer.parseInt(txtIdPelicula.getText()));
            
            if ( oPelicula != null ) { 
                //la pelicula existe
                txtIdPelicula.setText(String.valueOf(oPelicula.getId()));
                txtNombrePelicula.setText(oPelicula.getNombre());
                txtAnio.setText(String.valueOf(oPelicula.getAnio()));
                txtDirector.setText(oPelicula.getDirector());
                txtGenero.setText(oPelicula.getGenero());
                txtPrecioVenta.setText(String.valueOf(oPelicula.getPrecioVenta()));
                txtPrecioArriendo.setText(String.valueOf(oPelicula.getPrecioArriendo()));
                txtStock.setText(String.valueOf(oPelicula.getStock()));
            
            } else {
                //la pelicula no existe en el mapa
                JOptionPane.showMessageDialog(this, "No se encontro la Pelicula.");
            }
        
        }
        
    }//GEN-LAST:event_btnBuscarPeliculaActionPerformed

    private void btnLimpiarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarPeliculaActionPerformed
        // TODO add your handling code here:
        
        txtIdPelicula.setText("");
        txtNombrePelicula.setText("");
        txtAnio.setText("");
        txtDirector.setText("");
        txtGenero.setText("");
        txtPrecioVenta.setText("");
        txtPrecioArriendo.setText("");
        txtStock.setText("");
        
    }//GEN-LAST:event_btnLimpiarPeliculaActionPerformed

    private void btnAgregarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPeliculaActionPerformed
        // TODO add your handling code here:
        
        if( txtIdPelicula.getText().equals("") || txtIdPrestamo.getText().equals("") ) {
        
            JOptionPane.showMessageDialog(this, "Ingrese todos los datos");
        
        } else { 
            
            for(int i=0; i<tblPeliculas.getRowCount();i++){
                oModeloTabla.removeRow(i);
                i-=1;
            }
        
            Pelicula oPelicula = new Pelicula();
            Prestamo oPrestamo = new Prestamo();
            
            //busca la pelicula con el id ingresado en el txt
            oPelicula = oPelicula.buscarPelicula(mapaPeliculas, Integer.parseInt(txtIdPelicula.getText()));
            
            //se obtiene el prestamo que se desea modificar 
            oPrestamo = oPrestamo.buscarPrestamo(mapaPrestamos, Integer.parseInt(txtIdPrestamo.getText()));
            
            if ( oPelicula != null ) { 
                //la pelicula existe
                //oPrestamo.mapaPeliculas.put(oPelicula.getId(), oPelicula);
                oPrestamo.arrendarPelicula(oPrestamo, oPelicula);
                //oPrestamo.arrendarPelicula(mapaPrestamos, mapaTrabajadores, mapaPeliculas, oPelicula, txtRutTrabajador.getText(), txtRutCliente.getText(), txtFechaEntrega.getText(), txtFechaEntrega.getText());
                
                String [] datosPeliculas = new String[oModeloTabla.getColumnCount()];

                for (Map.Entry<Integer, Pelicula> entry : oPrestamo.mapaPeliculas.entrySet()) {

                    Pelicula oPelicula1 = new Pelicula();
                    oPelicula1 = entry.getValue();

                    datosPeliculas[0] = String.valueOf(oPelicula1.getId());
                    datosPeliculas[1] = oPelicula1.getNombre();
                    datosPeliculas[2] = String.valueOf(oPelicula1.getAnio());
                    datosPeliculas[3] = oPelicula1.getDirector();
                    datosPeliculas[4] = oPelicula1.getGenero();

                    oModeloTabla.addRow(datosPeliculas);

                }
                
                txtMontoPagar.setText(""+oPrestamo.getMontoAPagar());
                JOptionPane.showMessageDialog(this, "Se agrego la Pelicula con id: "+txtIdPelicula.getText()+" en el Prestamo con id: "+txtIdPrestamo.getText());
                txtIdPelicula.setText("");
                txtNombrePelicula.setText("");
                txtAnio.setText("");
                txtDirector.setText("");
                txtGenero.setText("");
                txtPrecioVenta.setText("");
                txtPrecioArriendo.setText("");
                txtStock.setText("");
            
            } else {
                //la pelicula no existe en el mapa
                JOptionPane.showMessageDialog(this, "No se encontro la Pelicula.");
            }
        
        }
        
    }//GEN-LAST:event_btnAgregarPeliculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarPrestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPelicula;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscarPelicula;
    private javax.swing.JButton btnBuscarPrestamo;
    private javax.swing.JButton btnLimpiarPelicula;
    private javax.swing.JButton btnLimpiarPrestamo;
    private javax.swing.JButton btnModificarPrestamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPeliculas;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtDirector;
    private javax.swing.JTextField txtFechaEntrega;
    private javax.swing.JTextField txtFechaPrestamo;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtIdPelicula;
    private javax.swing.JTextField txtIdPrestamo;
    private javax.swing.JTextField txtMontoPagar;
    private javax.swing.JTextField txtNombrePelicula;
    private javax.swing.JTextField txtPrecioArriendo;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtRutCliente;
    private javax.swing.JTextField txtRutTrabajador;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
